services:
  mongodb:
    image: mongo:latest
    container_name: zibal_mongodb
    ports:
      - "27017:27017"
    command: ["--quiet", "--bind_ip_all"]   # quieter logs
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      # Persistent data volume so init runs only once when empty
      - mongo_data:/data/db
      # Seed dump and init scripts (executed once when DB is empty)
      - ./dbseed/transaction.agz:/docker-entrypoint-initdb.d/transaction.agz:ro
      - ./docker/mongo-init.sh:/docker-entrypoint-initdb.d/00-mongo-init.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest
    container_name: zibal_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zibal_api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app:delegated  
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      python manage.py runserver 0.0.0.0:8000

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zibal_worker
    env_file: .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      MONGO_URI: mongodb://admin:secret@mongodb:27017/?authSource=admin
      MONGO_DB_NAME: zibal_db
      # Optional: tune retry/backoff via env
      NOTIFY_MAX_RETRIES: 5
      NOTIFY_BACKOFF_BASE: 2
      NOTIFY_BACKOFF_JITTER_SEC: 3
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      celery -A config worker -l info -Q notifications

volumes:
  mongo_data:
    name: zibal_mongo_data